# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82d9bf6e28e84c2f25bd9b22d4c2eb21cf578b79e28d176b8608a59405bc4fd1003d4110861bbc7bcda6a9356a8956cdcc2de1a84cc2b8bc972aa83000b752d0

test:
  secret_key_base: 0827c5414d7520fbd18ff233b6b8bab3da1134409d15b61ad6312a18ea22a2754d0068a479761b5f7915fe4cb191fb913f227d24cf1e5a9155f5f0297242d9a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
